using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace program
{
    // ObservableObject 
    class ExampleClass : ObservableObject 
    {

        // Decorate with the following to specify the place where the generator will paste the members
        #region Autogenerated Members
        #endregion // Autogenerated Members

        // Decorate with the following to specify the place where the generator will paste the properties
        #region Autogenerated Properties
        #endregion // Autogenerated Properties

    }
}
