using System;

namespace program
{
    class OtherExampleClass : ObservableObject
    {
        // Again, you must decorate with the following regions to allow pasting from the generator.

        #region Autogenerated Members

        #endregion // Autogenerated Members


        #region Autogenerated Properties

        #endregion // Autogenerated Properties
    }
}
